from Table.Table import Table

f1 = "classmates.csv"
f2 = "class1.csv"
t1 = Table(f1)
print(t1)
t1.save_table("class.csv")
print("---------------------------")
t2=t1.get_rows_by_number(1,3)
t2[0][0]='Петр'
print(t2)
print(t1)

print("---------------------------")
t2=t1.get_rows_by_number(1,3,True)
t2[0][0]='Сергей'
print(t2)
print(t1)

print("----------------------------------------------")
t1 = Table(f1)
t2=t1.get_rows_by_index(['Виктор', 'Петр'])
print(t2)
t2[0][0]='Сергей'
t2[1][-1]='1990'
print(t1)

t1 = Table(f1)
t2=t1.get_rows_by_index(['Виктор', 'Петр'],True)
print(t2)
t2[0][0]='Сергей'
t2[1][-1]='1990'
print(t1)

print("----------------------------------------------")
print(t1.get_column_types())
print(t1.get_column_types(False))
print("----------------------------------------------")
print(t1.get_values(1))
print(t1.get_values('Год рождения'))
print("----------------------------------------------")
print(t1.get_value(1))
print(t1.get_value('Год рождения'))
print("----------------------------------------------")
t1 = Table(f1)
t1.set_values(['Пекарь','Инженер','Сварщик'],1)
print(t1)
t1.set_values(['Фельдшер','Бухгалтер'],1)
print(t1)
t1.set_values(['Космонавт','Стример','Блогер','Фитнес-тренер'],'Профессия')
print(t1)
t1.set_value('Альпинист','Профессия')
print(t1)
t1.print_table()
print("----------------------------------------------")
t1 = Table(f1)
print(t1)
t1.tableSetType()
print(t1)
print("----------------------------------------------")
t1 = Table(f1)
t1.tableSetType()
print(t1.execute("add",2,1))
print(t1.execute("sub",2,1))
print(t1.execute("mul","Год рождения",2,3))
print(t1.execute("mul","Год рождения",2))
print(t1.execute("div","Год рождения",2))
print("----------------------------------------------")
t1 = Table(f1)
t1.tableSetType()
print(t1.filter_rows("eq",1985,2,1))
print(t1.filter_rows("ne",1985,2,1))
print()
print(t1.filter_rows("lt",1985,"Год рождения",1))
print(t1.filter_rows("le",1985,"Год рождения",1))
print()
print(t1.filter_rows("gt",1997,"Год рождения",1))
print(t1.filter_rows("ge",1997,"Год рождения",1))
print()
print("----------------------------------------------")
print(t1)
t1.filter_rows("eq",1985,2,1,copy_table=True)[1][-1]=1996
print(t1)
t1.filter_rows("eq",1985,2,1)[1][-1]=1998
print(t1)
print("----------------------------------------------")
t1 = Table(f2)
print(t1)
t1 = Table(f2,True)
print(t1)
print("----------------------------------------------")
t1 = Table(f1)
t1.data=t1.data[:1]
print(t1)
print(t1.get_values(1))
print(t1.get_value(1))
print(t1.filter_rows("ge",1997,"Год рождения",1))
print(t1.execute("div","Год рождения",2))
t1.set_values(['Фельдшер','Бухгалтер'],1)
t1.set_value('Альпинист','Профессия')
print(t1.get_column_types(False))
t2=t1.get_rows_by_index(['Виктор', 'Петр'],True)
t2=t1.get_rows_by_number(1,3,True)
